Apply workaround for Intel-16
Without this I see:
```
/boost/core/noncopyable.hpp(42): error: defaulted default constructor cannot be constexpr because the corresponding implicitly declared default constructor would not be constexpr
        BOOST_CONSTEXPR noncopyable() = default;
```
See: https://travis-ci.org/boostorg/type_traits/jobs/4722892817
Not sure if later Intel versions also require this... still working on that.